### ISSUE TITLE
Git conflict markers in the new issue form. 

### ISSUE THREAD

**Issue by calewis** [sstsimulator/sst-core#678]
Below is what I see when making a new issue:
```
New Issue for sst-core
----------------------
1 - Detailed description of problem or enhancement

2 - Describe how to reproduce

3 - What Operating system(s) and versions 

4 - What version of external libraries (Boost, MPI)

5 - Provide sha1 of all relevant sst repositories (sst-core, sst-elements, etc)

6 - Fill out Labels, Milestones, and Assignee fields as best possible

<<<<<<< HEAD
=======

>>>>>>> devel
```
Where did:
```
<<<<<<< HEAD
=======

>>>>>>> devel
``` 
come from?

**Comment by calewis** [comment]
Apparently git blame says it was @nmhamster :P

**Comment by nmhamster** [comment]
@calewis - it always says its @nmhamster fault. I believe this issue is fixed and am closing. Reopen if any more problems.

**Comment by calewis** [comment]
@nmhamster why did you close this? 

It's still an issue
<img width="960" alt="Screen Shot 2021-09-21 at 9 57 46 AM" src="https://user-images.githubusercontent.com/5229805/134184447-dd1e3e75-064e-44e4-9690-3fc153166612.png">
